#ifndef CONSTANTS_h
#define CONSTANTS_h

/**********
 * Contains system/build independent configuration details
 *********/

#define MILLIS_TO_SECONDES 1000
#define SECONDS_TO_MINUTES 60

#define ANT_NUM_CHANNELS 15

#define CADENCE_SENSOR_DEVICE_TYPE 122
#define CADENCE_SENSOR_TRANSMISSION_PERIOD 8102
#define SPEED_SENSOR_DEVICE_TYPE   123
#define SPEED_SENSOR_TRANSMISSION_PERIOD 8118

#define USB_DEBUG_LEVEL_INFO 3
#define USB_DEBUG_LEVEL_WARNING 2
#define USB_DEBUG_LEVEL_ERROR 1
#define USB_DEBUG_LEVEL_NONE 0

#endif // CONSTANTS_h
