/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sun Jul 14 22:19:04 2019. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ScanCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t AssignCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t RequestStatusCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t IdentifyCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t SetCountRateCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t Command_fields[6] = {
    PB_ONEOF_FIELD(type,   1, MESSAGE , ONEOF, STATIC  , FIRST, Command, scan, scan, &ScanCommand_fields),
    PB_ONEOF_FIELD(type,   2, MESSAGE , ONEOF, STATIC  , UNION, Command, assign, assign, &AssignCommand_fields),
    PB_ONEOF_FIELD(type,   3, MESSAGE , ONEOF, STATIC  , UNION, Command, request, request, &RequestStatusCommand_fields),
    PB_ONEOF_FIELD(type,   4, MESSAGE , ONEOF, STATIC  , UNION, Command, identify, identify, &IdentifyCommand_fields),
    PB_ONEOF_FIELD(type,   5, MESSAGE , ONEOF, STATIC  , UNION, Command, countRate, countRate, &SetCountRateCommand_fields),
    PB_LAST_FIELD
};

const pb_field_t SystemStatus_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t SensorCountStatus_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t SystemFaultStatus_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t SystemBootStatus_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t TombStoneStatus_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t Status_fields[6] = {
    PB_ONEOF_FIELD(type,   1, MESSAGE , ONEOF, STATIC  , FIRST, Status, system, system, &SystemStatus_fields),
    PB_ONEOF_FIELD(type,   2, MESSAGE , ONEOF, STATIC  , UNION, Status, count, count, &SensorCountStatus_fields),
    PB_ONEOF_FIELD(type,   3, MESSAGE , ONEOF, STATIC  , UNION, Status, fault, fault, &SystemFaultStatus_fields),
    PB_ONEOF_FIELD(type,   4, MESSAGE , ONEOF, STATIC  , UNION, Status, boot, boot, &SystemBootStatus_fields),
    PB_ONEOF_FIELD(type,   5, MESSAGE , ONEOF, STATIC  , UNION, Status, tomb, tomb, &TombStoneStatus_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Command, type.scan) < 65536 && pb_membersize(Command, type.assign) < 65536 && pb_membersize(Command, type.request) < 65536 && pb_membersize(Command, type.identify) < 65536 && pb_membersize(Command, type.countRate) < 65536 && pb_membersize(Status, type.system) < 65536 && pb_membersize(Status, type.count) < 65536 && pb_membersize(Status, type.fault) < 65536 && pb_membersize(Status, type.boot) < 65536 && pb_membersize(Status, type.tomb) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ScanCommand_AssignCommand_RequestStatusCommand_IdentifyCommand_SetCountRateCommand_Command_SystemStatus_SensorCountStatus_SystemFaultStatus_SystemBootStatus_TombStoneStatus_Status)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Command, type.scan) < 256 && pb_membersize(Command, type.assign) < 256 && pb_membersize(Command, type.request) < 256 && pb_membersize(Command, type.identify) < 256 && pb_membersize(Command, type.countRate) < 256 && pb_membersize(Status, type.system) < 256 && pb_membersize(Status, type.count) < 256 && pb_membersize(Status, type.fault) < 256 && pb_membersize(Status, type.boot) < 256 && pb_membersize(Status, type.tomb) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ScanCommand_AssignCommand_RequestStatusCommand_IdentifyCommand_SetCountRateCommand_Command_SystemStatus_SensorCountStatus_SystemFaultStatus_SystemBootStatus_TombStoneStatus_Status)
#endif


/* @@protoc_insertion_point(eof) */
