/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Mon Jul 15 00:03:05 2019. */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _IdentifyCommand {
    char dummy_field;
/* @@protoc_insertion_point(struct:IdentifyCommand) */
} IdentifyCommand;

typedef struct _RequestStatusCommand {
    char dummy_field;
/* @@protoc_insertion_point(struct:RequestStatusCommand) */
} RequestStatusCommand;

typedef struct _SensorCountStatus {
    char dummy_field;
/* @@protoc_insertion_point(struct:SensorCountStatus) */
} SensorCountStatus;

typedef struct _SetCountRateCommand {
    char dummy_field;
/* @@protoc_insertion_point(struct:SetCountRateCommand) */
} SetCountRateCommand;

typedef struct _SystemBootStatus {
    char dummy_field;
/* @@protoc_insertion_point(struct:SystemBootStatus) */
} SystemBootStatus;

typedef struct _SystemFaultStatus {
    char dummy_field;
/* @@protoc_insertion_point(struct:SystemFaultStatus) */
} SystemFaultStatus;

typedef struct _SystemStatus {
    char dummy_field;
/* @@protoc_insertion_point(struct:SystemStatus) */
} SystemStatus;

typedef struct _TombStoneStatus {
    char dummy_field;
/* @@protoc_insertion_point(struct:TombStoneStatus) */
} TombStoneStatus;

typedef struct _ChannelConfig {
    uint32_t channel_id;
    uint32_t device_type;
    uint32_t transmission_type;
/* @@protoc_insertion_point(struct:ChannelConfig) */
} ChannelConfig;

typedef struct _ScanCommand {
    uint32_t scan_time;
/* @@protoc_insertion_point(struct:ScanCommand) */
} ScanCommand;

typedef struct _Status {
    pb_size_t which_type;
    union {
        SystemStatus system;
        SensorCountStatus count;
        SystemFaultStatus fault;
        SystemBootStatus boot;
        TombStoneStatus tomb;
    } type;
/* @@protoc_insertion_point(struct:Status) */
} Status;

typedef struct _AssignCommand {
    pb_size_t config_count;
    ChannelConfig config[15];
/* @@protoc_insertion_point(struct:AssignCommand) */
} AssignCommand;

typedef struct _Command {
    pb_size_t which_type;
    union {
        ScanCommand scan;
        AssignCommand assign;
        RequestStatusCommand request;
        IdentifyCommand identify;
        SetCountRateCommand count_rate;
    } type;
/* @@protoc_insertion_point(struct:Command) */
} Command;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ScanCommand_init_default                 {0}
#define ChannelConfig_init_default               {0, 0, 0}
#define AssignCommand_init_default               {0, {ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default}}
#define RequestStatusCommand_init_default        {0}
#define IdentifyCommand_init_default             {0}
#define SetCountRateCommand_init_default         {0}
#define Command_init_default                     {0, {ScanCommand_init_default}}
#define SystemStatus_init_default                {0}
#define SensorCountStatus_init_default           {0}
#define SystemFaultStatus_init_default           {0}
#define SystemBootStatus_init_default            {0}
#define TombStoneStatus_init_default             {0}
#define Status_init_default                      {0, {SystemStatus_init_default}}
#define ScanCommand_init_zero                    {0}
#define ChannelConfig_init_zero                  {0, 0, 0}
#define AssignCommand_init_zero                  {0, {ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero}}
#define RequestStatusCommand_init_zero           {0}
#define IdentifyCommand_init_zero                {0}
#define SetCountRateCommand_init_zero            {0}
#define Command_init_zero                        {0, {ScanCommand_init_zero}}
#define SystemStatus_init_zero                   {0}
#define SensorCountStatus_init_zero              {0}
#define SystemFaultStatus_init_zero              {0}
#define SystemBootStatus_init_zero               {0}
#define TombStoneStatus_init_zero                {0}
#define Status_init_zero                         {0, {SystemStatus_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define ChannelConfig_channel_id_tag             1
#define ChannelConfig_device_type_tag            2
#define ChannelConfig_transmission_type_tag      3
#define ScanCommand_scan_time_tag                1
#define Status_system_tag                        1
#define Status_count_tag                         2
#define Status_fault_tag                         3
#define Status_boot_tag                          4
#define Status_tomb_tag                          5
#define AssignCommand_config_tag                 1
#define Command_scan_tag                         1
#define Command_assign_tag                       2
#define Command_request_tag                      3
#define Command_identify_tag                     4
#define Command_count_rate_tag                   5

/* Struct field encoding specification for nanopb */
extern const pb_field_t ScanCommand_fields[2];
extern const pb_field_t ChannelConfig_fields[4];
extern const pb_field_t AssignCommand_fields[2];
extern const pb_field_t RequestStatusCommand_fields[1];
extern const pb_field_t IdentifyCommand_fields[1];
extern const pb_field_t SetCountRateCommand_fields[1];
extern const pb_field_t Command_fields[6];
extern const pb_field_t SystemStatus_fields[1];
extern const pb_field_t SensorCountStatus_fields[1];
extern const pb_field_t SystemFaultStatus_fields[1];
extern const pb_field_t SystemBootStatus_fields[1];
extern const pb_field_t TombStoneStatus_fields[1];
extern const pb_field_t Status_fields[6];

/* Maximum encoded size of messages (where known) */
#define ScanCommand_size                         6
#define ChannelConfig_size                       18
#define AssignCommand_size                       300
#define RequestStatusCommand_size                0
#define IdentifyCommand_size                     0
#define SetCountRateCommand_size                 0
#define Command_size                             303
#define SystemStatus_size                        0
#define SensorCountStatus_size                   0
#define SystemFaultStatus_size                   0
#define SystemBootStatus_size                    0
#define TombStoneStatus_size                     0
#define Status_size                              2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
