version: '3'
services:
        mqtt:
                image: eclipse-mosquitto
                restart: always
                ports:
                        - "1883:1883"
                        - "9001:9001"
                volumes:
                        - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
